# Generated by Django 5.2.10 on 2026-04-09 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_schema', models.JSONField(help_text='JSON Schema for telemetry payload validation')),
                ('transformation_rules', models.JSONField(blank=True, default=dict, help_text='Rules for transforming raw telemetry payload')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telemetry_schemas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version'], name='idx_telemetry_schema_version'), models.Index(fields=['is_active'], name='idx_telemetry_schema_active')],
            },
        ),
    ]
